GET http://localhost:3010/admin/doctorlist

###
GET http://localhost:3010/userlist

###
GET http://localhost:3010/labtechlist

###
POST http://localhost:3010/doctor
Content-Type: application/json

{
    "mobile":"admin",
    "name":"admin"
}

###
POST http://localhost:3010/labtech
Content-Type: application/json

{
    "mobile":"admin",
    "name":"admin"
}

###
GET http://localhost:3010/

###
POST http://localhost:3010/login
Content-Type: application/json

{
    "ID":"admin",
    "password":"SUITS"
}

###
GET http://localhost:3010/counts

###
DELETE http://localhost:3010/doctor
Content-Type: application/json

{
    "mobile":"admin2"
}

###
DELETE http://localhost:3010/doctor
Content-Type: application/json

{
    "mobile":"admin2"
}

###
DELETE http://localhost:3010/user
Content-Type: application/json

{
    "memberid":"IDC0003"
}
